### ISSUE TITLE
Adding Rack label in Device target

### ISSUE THREAD

**Issue by geg347** [FlxPeters/netbox-plugin-prometheus-sd#109]
Hello,

First thank you for this project, it is very useful!

I needed to add the Rack label when requesting a Device as Prometheus target.

But by looking the code I saw 2 possibilities of implementing this.
So I forked the project and created 2 branches here :

- https://github.com/FlxPeters/netbox-plugin-prometheus-sd/compare/main...geg347:netbox-plugin-prometheus-sd:adding-rack-label-device-serializer-1

- https://github.com/FlxPeters/netbox-plugin-prometheus-sd/compare/main...geg347:netbox-plugin-prometheus-sd:adding-rack-label-device-serializer-2

Also I tried to blindly implement Unit test but I was not able to try it.

Can you tell me if we can implement this, please? If yes which one of the 2 possibilities seem the best (I will create the PR based on the best branch)?
Feel free to ask for any improvements.

Thanks and have a great day!
geg347

**Comment by FlxPeters** [comment]
Hey thanks for your contribution. I will check it soon and come back to you.

**Comment by FlxPeters** [comment]
Hey @geg347, please open a PR for the second one with an extra function to extract the label.
As soon as we have a PR tests should run and you can check it yourselfe.

Otherwise just run the tests locally, it's all Docker based. See: https://github.com/FlxPeters/netbox-plugin-prometheus-sd#development

**Comment by geg347** [comment]
Hello @FlxPeters,
Thanks for merging!
Do you plan to publish a new release or you are waiting for other issues to be implemented maybe.

**Comment by FlxPeters** [comment]
Release is on the way!
