### ISSUE TITLE
Include Site and Region as __meta labels

### ISSUE THREAD

**Issue by jeffbaier** [FlxPeters/netbox-plugin-prometheus-sd#118]
The current list of `__meta_netbox` labels is good, but I think it would be helpful to include Site and Region.

Forgive me if I have just missed them or if there is a good reason not to include them.

**Comment by jeffbaier** [comment]
I should clarify: I have only been working with Virtual Machines at this time so I have only been looking at `/api/plugins/prometheus-sd/virtual-machines/`

Just spent some time looking through the source code. It looks like `site` is included on Devices. For Virtual Machines, if the VM is attached to a Cluster only then is Site included in the __meta labels. I don't understand this reasoning, can anyone clarify?

**Comment by FlxPeters** [comment]
I have a similar case. My definition is a AWS account for an cluster, but also a VPC is possible. Depends on how your infrastructure is designed.

Feel free to add an pull request for missing fields.
