### ISSUE TITLE
Support for Device OOB IP

### ISSUE THREAD

**Issue by k0ste** [FlxPeters/netbox-plugin-prometheus-sd#129]
For a years NetBox users requested for OOB IP in DCIM https://github.com/netbox-community/netbox/issues/8137
Now this PR merged and will avail in NetBox 3.6 https://github.com/netbox-community/netbox/pull/13013

`netbox-plugin-prometheus-sd` shoud have `oob_ip` field accordingly

**Comment by FlxPeters** [comment]
Nice feature, would love to see a PR as soon as it's available in Netbox.
