### ISSUE TITLE
Add support for Netbox webhooks

### ISSUE THREAD

**Issue by 33Fraise33** [FlxPeters/netbox-plugin-prometheus-sd#131]
Hello,

Currently the sd plugin creates an api call for each job following the configured `refresh_interval` under the `http_sd_config` in prometheus ([http_sd_config](https://prometheus.io/docs/prometheus/latest/http_sd/)). 

This might create some load if you have quite some jobs for different device types running over different prometheus instances. 
It would be nice to let this plugin do the initial scrape on prometheus request and subscribe to changes through [Netbox webhooks](https://demo.netbox.dev/static/docs/additional-features/webhooks/) and dynamically update the sd result for prometheus based on the received changes from the Netbox webhook. 

This creates a kind of cache for netbox limiting the amount of database calls happening. 

I am unsure how in scope this is but it would be nice to have it as a feature that can be enabled on request (giving both options between in memory cache or not)

**Comment by FlxPeters** [comment]
I don't see the demand for this kind of complexity. At least my Netbox deployments doesn't have any performance issues when running the plugin. Also there should be a caching on the database.

Introducing a cache is nothing I want to do without a need.

I will let this issue open to catch some others feedback, but for now this won't be implemented.

**Comment by llamafilm** [comment]
I’m also seeing performance problems, see #156.
