### ISSUE TITLE
Include location label

### ISSUE THREAD

**Issue by llamafilm** [FlxPeters/netbox-plugin-prometheus-sd#149]
Is there a way to include Netbox `location` field as a label to Prometheus?  I organize devices using a site > room hierarchy, so I'm using location to mean the room.  Site represents a physical building here.

**Comment by llamafilm** [comment]
I'm brand new to Netbox so please let me know if there's something missing, but I went ahead and drafted a PR because it looks like a very simple addition.

**Comment by FlxPeters** [comment]
Included in relase 0.8.0-rc1
