### ISSUE TITLE
Update needed for Netbox 4.0

### ISSUE THREAD

**Issue by DatPenguin** [FlxPeters/netbox-plugin-prometheus-sd#176]
Hi,

There are some breaking changes in Netbox 4.0, including the following:

`from extras.plugins import PluginConfig` should be replaced by `from netbox.plugins import PluginConfig`.

I'm not sure what else needs to be changed, but is an update planned to be compatible with Netbox 4.0 ? Thanks :)

P.S.: [Here are the changes from Netbox Doc](https://docs.netbox.dev/en/stable/plugins/development/migration-v4/).

**Comment by FlxPeters** [comment]
Update is on the way: https://github.com/FlxPeters/netbox-plugin-prometheus-sd/pull/177

**Comment by FlxPeters** [comment]
Netbox > 4.0 compatibility has been implemented in v1.1.0: https://github.com/FlxPeters/netbox-plugin-prometheus-sd/releases/tag/v1.1.0
