### ISSUE TITLE
multiple exporters on target

### ISSUE THREAD

**Issue by cervajs** [FlxPeters/netbox-plugin-prometheus-sd#59]
is it possible to scrape multiple exporters on one target?
i.e. node_exporter on port 2000, mariadb_exporter on port 2001

how can i define exporter port?

**Comment by FlxPeters** [comment]
Sure you can have multiple exporters on a target. Just build two separate jobs in Prometheus where the target is included in both queries.

The plugin only provides all available info from netbox as labels. Ports and relabeling is up to your Prometheus config

**Comment by FlxPeters** [comment]
Closing for now. Please let me know if you need further assistance.
