### ISSUE TITLE
Netbox 3.4.0 - Prometheus-sd plugin doesn't work

### ISSUE THREAD

**Issue by pasettifabio** [FlxPeters/netbox-plugin-prometheus-sd#86]
Hi everybody,
I'm trying Netbox 3.4.0 with netbox-plugin-prometheus-sd and I can't see any device using the /api/plugins/prometheus-sd/devices API even if I have at least 1 device.

This is the request:

`GET http://netbox.local:8000/api/plugins/prometheus-sd/devices/`

and this is the answer:

`
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

[]
`

But I have at least 1 device (Dell R630 in state Active)

**Comment by FlxPeters** [comment]
Hey and thanks for your feedback. I haven't looked into netbox 3.4 yet, but I will check the issue soon.

**Comment by samoz83** [comment]
We're running 3.4.2 with the 0.5.0 and seems to be working okay here, the API lists all our devices.

**Comment by jsenecal** [comment]
I does work for us as well (v3.4.2)
